export const MOCK_NOTIFICATIONS = [
  {
    id: "1",
    _id: "1",
    title: "Placement Drive - TCS",
    message: "TCS is conducting a campus placement drive. Interested candidates can register through the portal.",
    category: "Placement",
    type: "Placement",
    priority: "high",
    viewed: false,
    timestamp: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
  },
  {
    id: "2",
    _id: "2",
    title: "Semester Results Published",
    message: "Your semester 4 results have been published. Check your academic portal for detailed marks.",
    category: "Result",
    type: "Result",
    priority: "medium",
    viewed: false,
    timestamp: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
  },
  {
    id: "3",
    _id: "3",
    title: "Tech Conference 2026",
    message: "Join us for an exciting tech conference featuring industry leaders. Registration is open until June 30.",
    category: "Event",
    type: "Event",
    priority: "medium",
    viewed: true,
    timestamp: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
  {
    id: "4",
    _id: "4",
    title: "Internship Opportunity - Google",
    message: "Google is offering summer internships for CS students. Application deadline: June 28. Apply now!",
    category: "Placement",
    type: "Placement",
    priority: "high",
    viewed: false,
    timestamp: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
  },
  {
    id: "5",
    _id: "5",
    title: "Library Extended Hours",
    message: "The library will remain open until 10 PM during the exam season for your convenience.",
    category: "Event",
    type: "Event",
    priority: "low",
    viewed: true,
    timestamp: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
  },
  {
    id: "6",
    _id: "6",
    title: "Grade Improvement Exam",
    message: "Students can now apply for grade improvement exams for previous semesters.",
    category: "Result",
    type: "Result",
    priority: "medium",
    viewed: false,
    timestamp: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
  },
  {
    id: "7",
    _id: "7",
    title: "Microsoft Hiring Drive",
    message: "Microsoft is hiring for Software Development roles. Registrations are now open in the placement portal.",
    category: "Placement",
    type: "Placement",
    priority: "high",
    viewed: true,
    timestamp: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
  },
  {
    id: "8",
    _id: "8",
    title: "Hackathon Registration",
    message: "Annual hackathon is here! Form teams of 3-4 and register by June 25. Prizes worth ₹2 lakhs!",
    category: "Event",
    type: "Event",
    priority: "high",
    viewed: false,
    timestamp: new Date(Date.now() - 1000 * 60 * 150).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 150).toISOString(),
  },
  {
    id: "9",
    _id: "9",
    title: "Campus Fee Payment Reminder",
    message: "Please ensure all pending semester fees are paid by June 30, 2026.",
    category: "Event",
    type: "Event",
    priority: "medium",
    viewed: true,
    timestamp: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
  },
  {
    id: "10",
    _id: "10",
    title: "Final Semester Exam Schedule",
    message: "The final semester exam schedule has been released. Check the academic calendar for details.",
    category: "Result",
    type: "Result",
    priority: "high",
    viewed: false,
    timestamp: new Date(Date.now() - 1000 * 60 * 200).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 200).toISOString(),
  },
];
